# this file contains default parameters for the refrigerator module. 
# override configs in config.yaml by copying the parameter name and 
# setting a new value
interval_seconds: 1800 # once an hour
door_sensor_pin: 18
# OLD URLS
#server: http://localhost:3000/api/fridgedata
#server: https://rvacf-test-bb7706080ec2.herokuapp.com/api/fridgedata
# server: https://al6mmf5bsd.execute-api.us-east-1.amazonaws.com/flaskBot/retrieveSensorData
# THE REAL URL
server: https://al6mmf5bsd.execute-api.us-east-1.amazonaws.com/prod/api/writeData

# discord bot
headers:
  Discord_header:
    Authorization: 'Bot ${token}'
    User-Agent: 'DiscordBot ${User-Agent}'
    Content-Type: 'application/json'
