# this file contains default parameters for the refrigerator module. 
# override configs in config.yaml by copying the parameter name and 
# setting a new value
interval_seconds: 5   
#server: http://localhost:3000/api/fridgedata
server: https://rvacf-test-bb7706080ec2.herokuapp.com/api/fridgedata
